# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'welcome_pane.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1120, 750)
        Form.setMinimumSize(QtCore.QSize(1120, 750))
        Form.setMaximumSize(QtCore.QSize(1120, 750))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/welcome_pane/images/main_pane_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.line = QtWidgets.QFrame(Form)
        self.line.setWindowModality(QtCore.Qt.NonModal)
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(0)
        self.line.setMidLineWidth(0)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 1, 1, 1)
        self.left_qw = QtWidgets.QWidget(Form)
        self.left_qw.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.left_qw.setObjectName("left_qw")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.left_qw)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtWidgets.QLabel(self.left_qw)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.model_train_btn = QtWidgets.QToolButton(self.left_qw)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.model_train_btn.sizePolicy().hasHeightForWidth())
        self.model_train_btn.setSizePolicy(sizePolicy)
        self.model_train_btn.setMinimumSize(QtCore.QSize(200, 60))
        self.model_train_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.model_train_btn.setStyleSheet("QToolButton{\n"
"    background-color:transparent;\n"
"    font: 87 20pt \"思源宋体 CN Heavy\";\n"
"}\n"
"QToolButton:hover{\n"
"    color:qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(0, 0, 0, 255), stop:0.05 rgba(14, 8, 73, 255), stop:0.36 rgba(28, 17, 145, 255), stop:0.6 rgba(126, 14, 81, 255), stop:0.75 rgba(234, 11, 11, 255), stop:0.79 rgba(244, 70, 5, 255), stop:0.86 rgba(255, 136, 0, 255), stop:0.935 rgba(239, 236, 55, 255));\n"
"}\n"
"QToolButton:pressed{\n"
"\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/train_pane/images/model_train.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.model_train_btn.setIcon(icon1)
        self.model_train_btn.setIconSize(QtCore.QSize(40, 40))
        self.model_train_btn.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.model_train_btn.setObjectName("model_train_btn")
        self.gridLayout_2.addWidget(self.model_train_btn, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.left_qw)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 2, 1, 1)
        self.train_recent_qw = QtWidgets.QWidget(self.left_qw)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.train_recent_qw.sizePolicy().hasHeightForWidth())
        self.train_recent_qw.setSizePolicy(sizePolicy)
        self.train_recent_qw.setObjectName("train_recent_qw")
        self.gridLayout_2.addWidget(self.train_recent_qw, 1, 0, 1, 3)
        self.gridLayout.addWidget(self.left_qw, 1, 0, 1, 1)
        self.right_qw = QtWidgets.QWidget(Form)
        self.right_qw.setObjectName("right_qw")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.right_qw)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_7 = QtWidgets.QLabel(self.right_qw)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 1, 1)
        self.model_predict_btn = QtWidgets.QToolButton(self.right_qw)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.model_predict_btn.sizePolicy().hasHeightForWidth())
        self.model_predict_btn.setSizePolicy(sizePolicy)
        self.model_predict_btn.setMinimumSize(QtCore.QSize(200, 60))
        self.model_predict_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.model_predict_btn.setStyleSheet("QToolButton{\n"
"    background-color:transparent;\n"
"    font: 87 20pt \"思源宋体 CN Heavy\";\n"
"}\n"
"QToolButton:hover{\n"
"    color:qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 0, 0, 255), stop:0.05 rgba(14, 8, 73, 255), stop:0.36 rgba(28, 17, 145, 255), stop:0.6 rgba(126, 14, 81, 255), stop:0.75 rgba(234, 11, 11, 255), stop:0.79 rgba(244, 70, 5, 255), stop:0.86 rgba(255, 136, 0, 255), stop:0.935 rgba(239, 236, 55, 255));\n"
"}\n"
"QToolButton:pressed{\n"
"\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/predict_pane/images/model_predict.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.model_predict_btn.setIcon(icon2)
        self.model_predict_btn.setIconSize(QtCore.QSize(40, 40))
        self.model_predict_btn.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.model_predict_btn.setArrowType(QtCore.Qt.NoArrow)
        self.model_predict_btn.setObjectName("model_predict_btn")
        self.gridLayout_3.addWidget(self.model_predict_btn, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.right_qw)
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 2, 1, 1)
        self.predict_recent_qw = QtWidgets.QWidget(self.right_qw)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.predict_recent_qw.sizePolicy().hasHeightForWidth())
        self.predict_recent_qw.setSizePolicy(sizePolicy)
        self.predict_recent_qw.setObjectName("predict_recent_qw")
        self.gridLayout_3.addWidget(self.predict_recent_qw, 1, 0, 1, 3)
        self.gridLayout.addWidget(self.right_qw, 1, 2, 1, 1)
        self.top_qw = QtWidgets.QWidget(Form)
        self.top_qw.setStyleSheet("QWidget#top_qw{\n"
"    border-image: url(:/welcome_pane/images/background2.jpg);\n"
"}\n"
"")
        self.top_qw.setObjectName("top_qw")
        self.label = QtWidgets.QLabel(self.top_qw)
        self.label.setGeometry(QtCore.QRect(250, 90, 131, 121))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(72)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
"    \n"
"    color: rgb(255, 149, 0);\n"
"    background-color:transparent;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.top_qw)
        self.label_2.setGeometry(QtCore.QRect(390, 110, 531, 91))
        font = QtGui.QFont()
        font.setFamily("站酷高端黑")
        font.setPointSize(36)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.top_qw)
        self.label_3.setGeometry(QtCore.QRect(510, 50, 121, 41))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(217, 217, 217);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.top_qw)
        self.label_4.setGeometry(QtCore.QRect(260, 190, 661, 61))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(217, 217, 217);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.toolButton = QtWidgets.QToolButton(self.top_qw)
        self.toolButton.setGeometry(QtCore.QRect(0, 335, 280, 40))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(12)
        self.toolButton.setFont(font)
        self.toolButton.setStyleSheet("QToolButton{\n"
"    color: rgb(225, 225, 225);\n"
"    background-color: transparent;\n"
"    margin-left: 40px;\n"
"}\n"
"QToolButton:hover{\n"
"    \n"
"}\n"
"QToolButton:clicked{\n"
"\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/welcome_pane/images/星地链接.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon3)
        self.toolButton.setIconSize(QtCore.QSize(25, 25))
        self.toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton.setObjectName("toolButton")
        self.toolButton_2 = QtWidgets.QToolButton(self.top_qw)
        self.toolButton_2.setGeometry(QtCore.QRect(280, 335, 280, 40))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(12)
        self.toolButton_2.setFont(font)
        self.toolButton_2.setStyleSheet("QToolButton{\n"
"    color: rgb(225, 225, 225);\n"
"    background-color: transparent;\n"
"    margin-left: 40px;\n"
"}\n"
"QToolButton:hover{\n"
"    \n"
"}\n"
"QToolButton:clicked{\n"
"\n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/welcome_pane/images/机器学习 (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_2.setIcon(icon4)
        self.toolButton_2.setIconSize(QtCore.QSize(25, 25))
        self.toolButton_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_2.setObjectName("toolButton_2")
        self.toolButton_3 = QtWidgets.QToolButton(self.top_qw)
        self.toolButton_3.setGeometry(QtCore.QRect(560, 335, 280, 40))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(12)
        self.toolButton_3.setFont(font)
        self.toolButton_3.setStyleSheet("QToolButton{\n"
"    color: rgb(225, 225, 225);\n"
"    background-color: transparent;\n"
"    margin-left: 40px;\n"
"}\n"
"QToolButton:hover{\n"
"    \n"
"}\n"
"QToolButton:clicked{\n"
"\n"
"}\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/welcome_pane/images/时空-空间.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_3.setIcon(icon5)
        self.toolButton_3.setIconSize(QtCore.QSize(25, 25))
        self.toolButton_3.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_3.setObjectName("toolButton_3")
        self.toolButton_4 = QtWidgets.QToolButton(self.top_qw)
        self.toolButton_4.setGeometry(QtCore.QRect(840, 335, 280, 40))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(12)
        self.toolButton_4.setFont(font)
        self.toolButton_4.setStyleSheet("QToolButton{\n"
"    color: rgb(225, 225, 225);\n"
"    background-color: transparent;\n"
"    margin-left: 40px;\n"
"}\n"
"QToolButton:hover{\n"
"    \n"
"}\n"
"QToolButton:clicked{\n"
"\n"
"}\n"
"")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/welcome_pane/images/波点面板.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_4.setIcon(icon6)
        self.toolButton_4.setIconSize(QtCore.QSize(25, 25))
        self.toolButton_4.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton_4.setObjectName("toolButton_4")
        self.gridLayout.addWidget(self.top_qw, 0, 0, 1, 3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "欢迎"))
        self.model_train_btn.setText(_translate("Form", "模型训练"))
        self.model_predict_btn.setText(_translate("Form", "模型推理"))
        self.label.setText(_translate("Form", "AI"))
        self.label_2.setText(_translate("Form", "环境参量反演软件"))
        self.label_3.setText(_translate("Form", "欢迎使用"))
        self.label_4.setText(_translate("Form", "一款利用星地数据，通过点面融合的机器学习方法进行环境参量反演的软件"))
        self.toolButton.setText(_translate("Form", "星地数据"))
        self.toolButton_2.setText(_translate("Form", "机器学习"))
        self.toolButton_3.setText(_translate("Form", "时空特征"))
        self.toolButton_4.setText(_translate("Form", "点面融合"))
import images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
